In [ ]:
!pip install 'git+https://github.com/SKTBrain/KoBERT.git#egg=kobert_tokenizer&subdirectory=kobert_hf'
!pip install torch==1.9.0 sentencepiece==0.1.96 transformers==4.8.1

### 모듈 임포트

In [ ]:
import torch
from transformers import BertModel
from kobert_tokenizer import KoBERTTokenizer

### 모델 불러오기

In [ ]:
model = BertModel.from_pretrained('skt/kobert-base-v1')
tokenizer = KoBERTTokenizer.from_pretrained('skt/kobert-base-v1')

### 문장 토큰화

In [ ]:
sentence1 = "민통선 바다를 건너왔다고 하여 산과 바다가 다르지는 않다고 생각했으나 그건 편견이었다. 월선포엔 태풍의 눈 같은 바다가 있었다. 헤라클라스의 풀무질 같은 거대한 힘의 물결이 소용돌이 치고 있었다. 바다가 아닌 폭우가 내린 다음날의 강줄기 같았다. 바다 건너엔 석모도 상주산이 솟구쳐 있었으나 살아 꿈틀거리고 있는 힘의 물살이 시선까지 빨아 당기고 있었다."
sentence2 = "햇살이 흐르는 수면에 찬란히 빛나는 것이, 거대한 은갈치가 휘감아 흐르는 듯했다. 어디서도 본 적 없는 바다가 월선포에 있었다. 교동대교가 생기기 전엔 육지와 섬을 잇는 유일한 통로였으나 지금은 빛바랜 ‘선착장 대합실’ 간판만 분주했던 옛 시절을 추억한다."

token_ids1 = tokenizer.encode(sentence1)
token_ids2 = tokenizer.encode(sentence2)

In [ ]:
token_ids1

tensor([[[   2, 2169, 7636, 6559, 2191, 6116,  881, 5691, 6990, 5439,  517,
          7815, 2640, 5468, 2191, 5330, 1562, 6113, 7327, 3153, 5439, 2705,
          7876, 1185, 5384, 4832, 5414, 7112,   54,  517, 7028, 6559, 7728,
          6909, 4720, 7750, 7095, 1535,  833, 2191, 5330, 3873,   54, 5046,
          6003, 7568, 6003, 6676, 4888, 6228, 7350,  833,  862, 5827, 5211,
          7095, 2135, 5415, 7096, 2822, 7003, 5868, 7096,  517, 7484, 3873,
            54, 2191, 5330, 3105, 4876, 5330, 1445, 1578, 7095,  807, 7292,
          5561,  830, 6828,   54, 2191,  881, 5691, 6909, 2732, 6213, 5859,
          2658, 7276, 6516, 7096,  517, 6620, 5495, 7443, 3871, 7075, 2644,
          1356, 7670, 5382, 5439, 3860, 5211, 7095, 2135, 6519, 7096, 2959,
          6559, 5592, 2562, 6797, 1618, 5561, 5439, 3873,   54,    3]]])

### 토큰 텐서화

In [ ]:
token_ids1 = torch.tensor(token_ids1).unsqueeze(0)
token_ids2 = torch.tensor(token_ids2).unsqueeze(0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  


In [ ]:
token_ids1[0]

tensor([[   2, 2169, 7636, 6559, 2191, 6116,  881, 5691, 6990, 5439,  517, 7815,
         2640, 5468, 2191, 5330, 1562, 6113, 7327, 3153, 5439, 2705, 7876, 1185,
         5384, 4832, 5414, 7112,   54,  517, 7028, 6559, 7728, 6909, 4720, 7750,
         7095, 1535,  833, 2191, 5330, 3873,   54, 5046, 6003, 7568, 6003, 6676,
         4888, 6228, 7350,  833,  862, 5827, 5211, 7095, 2135, 5415, 7096, 2822,
         7003, 5868, 7096,  517, 7484, 3873,   54, 2191, 5330, 3105, 4876, 5330,
         1445, 1578, 7095,  807, 7292, 5561,  830, 6828,   54, 2191,  881, 5691,
         6909, 2732, 6213, 5859, 2658, 7276, 6516, 7096,  517, 6620, 5495, 7443,
         3871, 7075, 2644, 1356, 7670, 5382, 5439, 3860, 5211, 7095, 2135, 6519,
         7096, 2959, 6559, 5592, 2562, 6797, 1618, 5561, 5439, 3873,   54,    3]])

### 문장 표현 추출

In [ ]:
representation1 = model(token_ids1[0])
representation2 = model(token_ids2[0])

ValueError: ignored

In [ ]:
cls_rep1 = representation1.last_hidden_state[:, 0, :]
cls_rep2 = representation2.last_hidden_state[:, 0, :]

In [ ]:
numpy_cls_rep1 = cls_rep1.detach().numpy()
numpy_cls_rep2 = cls_rep2.detach().numpy()

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(numpy_cls_rep1, numpy_cls_rep2)

array([[0.86600757]], dtype=float32)

### Class화

In [ ]:
!pip install 'git+https://github.com/SKTBrain/KoBERT.git#egg=kobert_tokenizer&subdirectory=kobert_hf'
!pip install torch==1.9.0 sentencepiece==0.1.96 transformers==4.8.1

  Cloning https://github.com/SKTBrain/KoBERT.git to /tmp/pip-install-hnj4dguf/kobert-tokenizer_3c95e3ebc8314454a311fa300bf8e547
  Running command git clone -q https://github.com/SKTBrain/KoBERT.git /tmp/pip-install-hnj4dguf/kobert-tokenizer_3c95e3ebc8314454a311fa300bf8e547


In [ ]:
import torch
from transformers import BertModel
from kobert_tokenizer import KoBERTTokenizer
from sklearn.metrics.pairwise import cosine_similarity


class SentenceSimilarity:
  def __init__(self):
    self.model = BertModel.from_pretrained('skt/kobert-base-v1')
    self.tokenizer = KoBERTTokenizer.from_pretrained('skt/kobert-base-v1')

  def run(self, sentence1, sentence2):
    token_ids1 = self.tokenizer.encode(sentence1)
    token_ids2 = self.tokenizer.encode(sentence2)

    unsqueeze_token_ids1 = torch.tensor(token_ids1).unsqueeze(0)
    unsqueeze_token_ids2 = torch.tensor(token_ids2).unsqueeze(0)

    representation1 = self.model(unsqueeze_token_ids1)
    representation2 = self.model(unsqueeze_token_ids2)

    cls_rep1 = representation1.last_hidden_state[:, 0, :]
    cls_rep2 = representation2.last_hidden_state[:, 0, :]

    numpy_cls_rep1 = cls_rep1.detach().numpy()
    numpy_cls_rep2 = cls_rep2.detach().numpy()

    return cosine_similarity(numpy_cls_rep1, numpy_cls_rep2)

In [ ]:
test_class = SentenceSimilarity()

sentence1 = "고양이가 세상에서 제일 귀엽다."
sentence2 = "고양이 보다는 강아지가 더 귀엽지."

test_class.run(sentence1, sentence2)

array([[0.81078124]], dtype=float32)